### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by lulavc** [anirudhmalik/xhunter#41]
sometimes the app force close when u try to access whatsapp. The always crash when i try to access any mobile on whatsapp loot.

```
android.database.sqlite.SQLiteException: no such table: chat_view (code 1 SQLITE_ERROR): , while compiling: SELECT chat_view.raw_string_jid AS id, messages.key_from_me AS isFromMe, messages.media_mime_type AS isMedia, messages.data, max(messages.timestamp) AS timestamp FROM chat_view LEFT OUTER JOIN messages on messages.key_remote_jid = chat_view.raw_string_jid WHERE chat_view.hidden = 0 GROUP BY chat_view.raw_string_jid, chat_view.subject, chat_view.created_timestamp ORDER BY max(messages.timestamp) desc
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1485)
	at com.xhunter.AppBuilderModule.readDB(AppBuilderModule.java:115)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by anirudhmalik** [comment]
> sometimes the app force close when u try to access whatsapp. The always crash when i try to access any mobile on whatsapp loot.
> 
> ```
> android.database.sqlite.SQLiteException: no such table: chat_view (code 1 SQLITE_ERROR): , while compiling: SELECT chat_view.raw_string_jid AS id, messages.key_from_me AS isFromMe, messages.media_mime_type AS isMedia, messages.data, max(messages.timestamp) AS timestamp FROM chat_view LEFT OUTER JOIN messages on messages.key_remote_jid = chat_view.raw_string_jid WHERE chat_view.hidden = 0 GROUP BY chat_view.raw_string_jid, chat_view.subject, chat_view.created_timestamp ORDER BY max(messages.timestamp) desc
> 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
> 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
> 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
> 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
> 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
> 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
> 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
> 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
> 	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1485)
> 	at com.xhunter.AppBuilderModule.readDB(AppBuilderModule.java:115)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
> 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
> 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
> 	at android.os.Looper.loopOnce(Looper.java:210)
> 	at android.os.Looper.loop(Looper.java:299)
> 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
> 	at java.lang.Thread.run(Thread.java:920)
> ```

Was there any chat on that WhatsApp account or you just tested on fresh WhatsApp account.
It seems that when sql query is made on `msgstore.db` it doesn't have `chat_view` table. If WhatsApp db have chats then this table must be there. 
Can you some how run sql query to list all tables on this msgstore.db file and share. 
this file is located here `/sdcard/XHUNTER/<device_name>/msgstore.db`

**Comment by lulavc** [comment]
This error was on a phone that installed GB Whatsapp. One point to consider is to use a good version of GB Whatsapp. It happens on all phones that i try to access the whatsapp conversation or data thru loot.

**Comment by anirudhmalik** [comment]
It is happening due to corrupt db file. fixing it soon
