### ISSUE TITLE
what's the issue here?

### ISSUE THREAD

**Issue by RubenSubba** [anirudhmalik/xhunter#50]
`error: TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (/home/ruben/Documents/xhunter/node_modules/metro/src/Bundler.js:48:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/home/ruben/Documents/xhunter/node_modules/metro/src/lib/transformHelpers.js:101:12)
    at async processModule (/home/ruben/Documents/xhunter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (/home/ruben/Documents/xhunter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/home/ruben/Documents/xhunter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/home/ruben/Documents/xhunter/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/home/ruben/Documents/xhunter/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)

`

**Comment by anirudhmalik** [comment]
Use `node -v` to check your node version. My node version is `v16.14.0` so I you are using v17 or other please downgrade it.
then retry building.

**Comment by RubenSubba** [comment]
> Use `node -v` to check your node version. My node version is `v16.14.0` so I you are using v17 or other please downgrade it. then retry building.

fixed this issue but app auto closing after splash screen :(

**Comment by anirudhmalik** [comment]
> > Use `node -v` to check your node version. My node version is `v16.14.0` so I you are using v17 or other please downgrade it. then retry building.
> 
> fixed this issue but app auto closing after splash screen :(

It is happening because you need to install some npm packages.
`cd nodejs-assets/nodejs-modules`
`npm install`
