### ISSUE TITLE
Binding to instagram doesn't work 

### ISSUE THREAD

**Issue by uglykid69** [anirudhmalik/xhunter#66]
Hey dev.

Im using xhunter from past 1 week and the app is really good. Binding into whatsapp works flawlessly but
I tried to bind to instagram and it binds the payload but doesn't gives back the connection.

I tried to manually bind the payload

Here are the problem i faced

There is no MainTabActivity.

Second i tried Bind to LauncherActivity.smali and it throws this error

USER_COMMENT=null
ANDROID_VERSION=12
APP_VERSION_NAME=232.0.0.16.114
BRAND=Xiaomi
PHONE_MODEL=Redmi Note 7 Pro
CUSTOM_DATA=
STACK_TRACE=java.lang.NoClassDefFoundError: Failed resolution of: Lio/socket/emitter/Emitter$Listener;
 at com.xhunter.client.Payload.start(Payload.java:66)
 at com.instagram.mainactivity.LauncherActivity.onCreate(Unknown Source:27)
 at android.app.Activity.performCreate(Activity.java:8057)
 at android.app.Activity.performCreate(Activity.java:8037)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7872)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.ClassNotFoundException: io.socket.emitter.Emitter$Listener
 ... 18 more
java.lang.ClassNotFoundException: io.socket.emitter.Emitter$Listener
 at com.xhunter.client.Payload.start(Payload.java:66)
 at com.instagram.mainactivity.LauncherActivity.onCreate(Unknown Source:27)
 at android.app.Activity.performCreate(Activity.java:8057)
 at android.app.Activity.performCreate(Activity.java:8037)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7872)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

My device: redmi note 7 pro
Android version 12L
Browser: Chrome latest

**Comment by uglykid69** [comment]
Site link 

https://www.instamod.net/2021/07/instapro-latest-version-apk-download.html?m=1

Download link

https://www.mediafire.com/file/7zbcwh271eb0at9/InstaPro+v9.35F_By.SamMods_sign.apk/file

I choose this because why would someone delete there orginal instagram if there aint any new feature into the apk im providing

**Comment by uglykid69** [comment]
> Which Instagram version are you using to merge the payload, can you send the payload link please 

Here
